LeagueManagerWebApp/LeagueManagerWebApp/ViewModels/ScoreViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LeagueManagerWebApp.Models;

namespace LeagueManagerWebApp.ViewModels
{
    public class ScoreViewModel
    {
        public List<MatchupModel> Matchups { get; set; }
        public List<PlayerViewModel> Players { get; set; }
        public List<LeagueModel> Leagues { get; set; }

        public ScoreViewModel(List<MatchupModel> matchups, List<LeagueModel> leagues)
        {
            Matchups = matchups;
            Leagues = leagues;
        }
    }

    
}

LeagueManagerWebApp/LeagueManagerWebApp/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LeagueManagerWebApp.Areas.Identity.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Controllers/AdministratorController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using LeagueManagerWebApp.Data;
using LeagueManagerWebApp.Interfaces;
using LeagueManagerWebApp.Models;
using LeagueManagerWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeagueManagerWebApp.Controllers
{


    public class AdministratorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAdministratorService _administratorService;
        private readonly AdminViewModel _viewModel = new AdminViewModel();

        public AdministratorController(ApplicationDbContext context, IAdministratorService administratorService)
        {
            _administratorService = administratorService;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                _viewModel.LeagueList = await _context.LeagueModel.ToListAsync();
                _viewModel.PlayerList = await _context.PlayerModel.ToListAsync();
                _viewModel.AchievementList = await _context.AchievementModel.ToListAsync();
                _viewModel.EventsList = await _context.EventModel.ToListAsync();
                return View(_viewModel);
            }

            return View("AccessDenied");
        }

        #region VIEWS

        public IActionResult PlayerCreator()
        {
            return View("PlayerCreatorView");
        }

        public IActionResult AchievementsCreator()
        {
            return View("AchievementsCreatorView");
        }

        public IActionResult LeagueCreator()
        {
            return View("LeagueCreatorView");
        }

        public IActionResult PlayerEditor(int? id)
        {
            return View("PlayerEditorView", id);
        }

        public IActionResult AchievementEditor(int? id)
        {

            return View("AchievementEditorView", _context.AchievementModel.Find(id));
        }

        public IActionResult LeagueEditor(int? id)
        {
            return View("LeagueEditorView", id);
        }

        public IActionResult LeagueStarter()
        {
            return View("LeagueStarterView", _context.LeagueModel.ToList());
        }

        public IActionResult AddScore()
        {
            var viewModel = new ScoreViewModel(null, _context.LeagueModel.ToList());
            
            return View("ScoreView", viewModel);
        }

        #endregion

        #region CRUD
        [HttpPost]
        public async Task<IActionResult> CreatePlayer(PlayerModel model)
        {
            await _administratorService.CreatePlayer(model, _context);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateAchievement(AchievementModel model)
        {
            await _administratorService.CreateAchievement(model, _context);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> CreateLeague(LeagueModel model)
        {
            var result = await _administratorService.CreateLeague(model, _context);
            if (result == 1)
            {
                return View("PlayersError");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditPlayer(PlayerModel model)
        {
            await _administratorService.EditPlayer(model, _context);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditAchievement(AchievementModel model)
        {
            await _administratorService.EditAchievement(model, _context);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditLeague(LeagueModel model)
        {
            await _administratorService.EditLeague(model, _context);
            return RedirectToAction("Index");
        }

        public IActionResult DeletePlayer(int? id)
        {
            _administratorService.DeletePlayer(id, _context);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteLeague(int? id)
        {
            _administratorService.DeleteLeague(id, _context);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteAchievement(int? id)
        {
            _administratorService.DeleteAchievement(id, _context);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteEvent(int? id)
        {
            _administratorService.DeleteEvent(id, _context);
            return RedirectToAction("Index");
        }

        #endregion

        [HttpPost]
        public IActionResult StartLeague(LeagueModel model)
        {
            _administratorService.StartLeague(model, _context);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult GetLeagueMatchups(LeagueModel league)
        {
            var chosenLeague = _context.LeagueModel.First(a=>a.Name==league.Name);
            var viewModel = new ScoreViewModel(_context.MatchupModel.ToList().Where(a=>a.LeagueId == chosenLeague.Id).ToList(), _context.LeagueModel.ToList());
            return View("ScoreView", viewModel);
        }
    
        public IActionResult AddScoreFinal(int? id, int EventId)
        {
            var model = _context.MatchupModel.First(a=>a.Id==id);
            return View("ScoreSheetView", model);
        }

        [HttpPost]
        public IActionResult PrepareMatchup(string EventId, string Player1, string Player2)
        {
            var matchup = new MatchupModel();
            matchup.Player1 = Player1;
            matchup.Player2 = Player2;
            matchup.Winner = Player1;
            matchup.EventId = Convert.ToInt32(EventId);
            return SubmitScore(matchup);
        }

        
        public IActionResult SubmitScore(MatchupModel model)
        {
            _administratorService.SubmitScore(model, _context);
            return RedirectToAction("Index");
        }

        public IActionResult StartEvent(int? id)
        {
            return View(_administratorService.StartEvent(id, _context));
        }

        public IActionResult CloseVoting(int? id)
        {
            _administratorService.CloseVoting(id, _context);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditEvent(int? id)
        {
            return View("EventEditView", _context.EventModel.Find(id));
        }

        [HttpPost]
        public async Task<IActionResult> EditEvent(EventModel model)
        {
            await _administratorService.EditEvent(model, _context);
            return RedirectToAction("Index");
        }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/AccessDenied.cshtml
@page


<header>
    <h1 class="text-danger">Access Denied</h1>
    <p class="text-danger">You do not have access to this resource.</p>
</header>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/AchievementEditorView.cshtml
@model AchievementModel
@{
    ViewData["Title"] = "AchievementEditorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid" style="margin-top: 10%">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="EditAchievement" method="post">
            <fieldset>
                <legend>Achievement Editor</legend>
                <input type="hidden" value="@Model" name="Id" />
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col">
                            Player name: <br />
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col">
                            Description: <br />
                        </div>
                        <div class="col">
                            <textarea form="data" cols="20" rows="10" name="Description"></textarea>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col">
                            Points: <br />
                        </div>
                        <div class="col">
                            <input type="number" name="MatchesPlayed" />
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col">
                            <input class="btn btn-primary" type="submit" />
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/AchievementsCreatorView.cshtml
@{
    ViewData["Title"] = "AchievementsCreatorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AchievementsCreatorView</h2>

<div class="container-fluid">
    <div class="row justify-content-center">
        <form id="data" asp-controller="Administrator" asp-action="CreateAchievement" method="post">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        Achievement name: <br />
                    </div>
                    <div class="col">
                        <input type="text" id="Name" name="Name" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Description: <br />
                    </div>
                    <div class="col">
                        <textarea form="data" cols="20" rows="10" name="Description"></textarea>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Points: <br />
                    </div>
                    <div class="col">
                        <input type="number" id="Points" name="Points" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/EventEditView.cshtml
@model EventModel
@{ 
    ViewData["Title"] = "EventEditView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function() {
        $("#ui-datepicker").datepicker();
    });
</script>
<body>
<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="EditEvent" method="post">
            <input type="hidden" value="@Model.Id" name="Id" />
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        Winner: <br />
                    </div>
                    <div class="col">
                        <input type="text" name="Winner" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Date: <br />
                    </div>
                    <div class="col">
                        <input name="Date" id="ui-datepicker"/>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Finished <br />
                    </div>
                    <div class="col">
                        @Html.CheckBoxFor(m=>m.isFinished)
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/EventFinished.cshtml
@{
    ViewData["Title"] = "EventFinished";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EventFinished</h2>
<p>
    This event is finished.
</p>
<p>
    <a asp-action="Index">Back</a>
</p>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/Index.cshtml
@model LeagueManagerWebApp.ViewModels.AdminViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="row">
        <div class="col">
            <a class="btn btn-primary btn-block" href="@Url.Action("PlayerCreator", "Administrator")">Player Creator</a>
        </div>
        <div class="col">
            <a class="btn btn-primary btn-block" href="@Url.Action("AchievementsCreator", "Administrator")">Achievements Creator</a>
        </div>
        <div class="col">
            <a class="btn btn-primary btn-block" href="@Url.Action("LeagueCreator", "Administrator")">League Creator</a>
        </div>
        <div class="col">
            <a class="btn btn-primary btn-block" href="@Url.Action("LeagueStarter", "Administrator")">League Starter</a>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            Id
                        </th>
                        <th scope="col">
                            Name
                        </th>
                        <th scope="col">
                            Elo
                        </th>
                        <th scope="col">
                            Has voted?
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.PlayerList != null)
                    {
                        foreach (var elem in Model.PlayerList)
                        {
                            <tr>
                                <td scope="row" data-label="Id">
                                    @elem.Id
                                </td>
                                <td data-label="Nick">
                                    @elem.Name
                                </td>
                                <td data-label="Elo">
                                    @elem.Elo
                                </td>
                                <td data-label="Has voted">
                                    @elem.HasVoted
                                </td>
                                <td>
                                    <a asp-action="DeletePlayer" asp-route-id="@elem.Id">Delete</a>|
                                    <a asp-action="PlayerEditor" asp-route-id="@elem.Id">Edit</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        <div class="col-6">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            Id
                        </th>
                        <th scope="col">
                            Name
                        </th>
                        <th scope="col">
                            Players
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.LeagueList != null)
                    {
                        foreach (var elem in Model.LeagueList)
                        {
                            <tr>
                                <td scope="row" data-label="Id">
                                    @elem.Id
                                </td>
                                <td data-label="Nazwa">
                                    @elem.Name
                                </td>
                                <td data-label="Gracze">
                                    @elem.Players
                                </td>
                                <td data-label="Akcje">
                                    <a asp-action="DeleteLeague" asp-route-id="@elem.Id">Delete</a>|
                                    <a asp-action="LeagueEditor" asp-route-id="@elem.Id">Edit</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            Id
                        </th>
                        <th scope="col">
                            Format
                        </th>
                        <th scope="col">
                            League
                        </th>
                        <th scope="col">
                            Is finished
                        </th>
                        <th scope="col">
                            Winner
                        </th>
                        <th scope="col">
                            Date
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.EventsList != null)
                    {
                        foreach (var elem in Model.EventsList)
                        {
                            <tr>
                                <td scope="row" data-label="Id">
                                    @elem.Id
                                </td>
                                <td data-label="Format">
                                    @elem.Format
                                </td>
                                <td data-label="Liga">
                                    @elem.LeagueId
                                </td>
                                <td data-label="isFinished">
                                    @elem.isFinished
                                </td>
                                <td data-label="Zwycięzca">
                                    @elem.Winner
                                </td>
                                <td data-label="Data">
                                    @elem.Date
                                </td>
                                <td data-label="Akcje">
                                    <a asp-action="DeleteEvent" asp-route-id="@elem.Id">Delete</a>|

                                    <a asp-action="StartEvent" asp-route-id="@elem.Id">Start</a>|

                                    <a asp-action="CloseVoting" asp-route-id="@elem.Id">Close Voting</a>|

                                    <a asp-action="EditEvent" asp-route-id="@elem.Id">Edit</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            Id
                        </th>
                        <th scope="col">
                            Name
                        </th>
                        <th scope="col">
                            Points
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.AchievementList != null)
                    {
                        foreach (var elem in Model.AchievementList)
                        {
                            <tr>
                                <td scope="row" data-label="Id">
                                    @elem.Id
                                </td>
                                <td data-label="Nazwa">
                                    @elem.Name
                                </td>
                                <td data-label="Punkty">
                                    @elem.Points
                                </td>
                                <td data-label="Akcje">
                                    <a asp-action="DeleteAchievement" asp-route-id="@elem.Id">Delete</a>|
                                    <a asp-action="AchievementEditor" asp-route-id="@elem.Id">Edit</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/LeagueCreatorView.cshtml
@{
    ViewData["Title"] = "LeagueCreatorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="CreateLeague" method="post">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        League name: <br />
                    </div>
                    <div class="col">
                        <input type="text" id="Name" name="Name" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Players: <br />
                    </div>
                    <div class="col">
                        <input type="text" id="Players" name="Players" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/LeagueEditorView.cshtml
@model int?
@{
    ViewData["Title"] = "LeagueEditorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LeagueEditorView</h2>

<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="EditLeague" method="post">
            <input type="hidden" value="@Model" name="Id" />
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        Player name: <br />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Players: <br />
                    </div>
                    <div class="col">
                        <textarea form="data" cols="20" rows="10" name="Players"></textarea>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/PlayerCreatorView.cshtml
@{
    ViewData["Title"] = "PlayerCreatorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PlayerCreatorView</h2>

<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="CreatePlayer" method="post">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        Player name: <br />
                    </div>
                    <div class="col">
                        <input type="text" id="Name" name="Name" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit"/>
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/PlayerEditorView.cshtml
@model int?
@{
    ViewData["Title"] = "PlayerEditorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PlayerEditorView</h2>

<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="EditPlayer" method="post">
            <input type="hidden" value="@Model" name="Id" />
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        Player name: <br />
                    </div>

                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Elo: <br />
                    </div>
                    <div class="col">
                        <input type="number" name="Elo" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Matches played: <br />
                    </div>
                    <div class="col">
                        <input type="number" name="MatchesPlayed" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Wins: <br />
                    </div>
                    <div class="col">
                        <input type="number" name="Wins" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Losses: <br />
                    </div>
                    <div class="col">
                        <input type="number" name="Losses" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Achievement score: <br />
                    </div>
                    <div class="col">
                        <input type="number" name="AchievementScore" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Has voted: <br />
                    </div>
                    <div class="col">
                        <input type="text" name="HasVoted" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/PlayersError.cshtml
@{
    ViewData["Title"] = "PlayersError";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PlayersError</h2>
Add players first!
<a class="btn btn-outline-primary btn-lg" href="@Url.Action("Index", "Administrator")">Home</a>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/ScoreSheetView.cshtml
@model MatchupModel
@{
    ViewData["Title"] = "ScoreSheetView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ScoreSheetView</h2>

<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Administrator" asp-action="SubmitScore" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="LeagueId" />
            <input type="hidden" asp-for="Player1" />
            <input type="hidden" asp-for="Player2" />
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col">
                        Winner: <br />
                    </div>
                    <div class="col">
                        <select id="Winner" name="Winner">
                            <option value="@Model.Player1">@Model.Player1</option>
                            <option value="@Model.Player2">@Model.Player2</option>
                        </select>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Administrator/StartEvent.cshtml
@model LeagueManagerWebApp.ViewModels.EventViewModel
@{
    ViewData["Title"] = "StartEvent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>StartEvent</h2>
<form asp-controller="Administrator" asp-action="PrepareMatchup">
    <input type="hidden" asp-for="Event.Id" name="EventId" id="EventId" />
    Winner:
    <select id="Player1" name="Player1">
        @foreach (var elem in Model.Players)
        {
            <option value="@elem.Name">@elem.Name</option>
        }
    </select>
    Loser:
    <select id="Player2" name="Player2">
        @foreach (var elem in Model.Players)
        {
            <option value="@elem.Name">@elem.Name</option>
        }
    </select>
    <input type="submit" />
</form>