LeagueManagerWebApp/LeagueManagerWebApp/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeagueManagerWebApp.Data;
using LeagueManagerWebApp.Dto;
using LeagueManagerWebApp.Interfaces;
using LeagueManagerWebApp.ViewModels;

namespace LeagueManagerWebApp.Controllers
{
    
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEventService _eventService;

        public EventController(ApplicationDbContext context, IEventService eventService)
        {
            _eventService = eventService;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(await _context.EventModel.ToListAsync());
            }

            return Redirect("/Identity/Account/Login");
        }

        public IActionResult Voting(int? id)
        {
            if (_context.PlayerModel.First(a => a.User == ControllerContext.HttpContext.User.Identity.Name).HasVoted ==
                false)
            {
                var model = _context.VotingModel.First(a => a.Id == id);
                var dto = new VotingDto();
                dto.Id = model.Id;
                dto.EventId = Convert.ToInt32(id);
                return View("Voting", dto);
            }

            return View("AlreadyVoted", _context.VotingModel.First(a => a.Id == id));
        }

        [HttpPost]
        public IActionResult SubmitVote(VotingDto model)
        {
            if (_eventService.SubmitVote(model, _context, _context.PlayerModel.First(a=>a.User == ControllerContext.HttpContext.User.Identity.Name).Name))
            {
                return View("Index", _context.EventModel.ToList());
            }

            return View("PollClosed");
        }

        public IActionResult VotingResults(int? id)
        {
            var viewmodel = new VotingResultViewModel();
            var model = _context.VotingModel.Find(id);
            Dictionary<string, int> dict = new Dictionary<string, int>();
            dict.Add("Backdraft",model.Back);
            dict.Add("Standard", model.Stand);
            dict.Add("Modern", model.Mod);
            dict.Add("Pauper", model.Pau);
            dict.Add("Rainbow", model.Rain);
            dict.Add("Draft", model.Draft);
            dict.Add("Singleton", model.Sing);
            dict.Add("Tribal", model.Tri);
            dict.Add("Peasant", model.Pea);
            dict.Add("Warband", model.War);
            Dictionary<string, int> output = dict.OrderBy(o => o.Value).Reverse().ToDictionary(p => p.Key,o=>o.Value);
            viewmodel.formats = output;
            viewmodel.winner = model.Winner;
            return View("VotingResult", viewmodel);

        }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Controllers/LeagueController.cs
using LeagueManagerWebApp.Data;
using LeagueManagerWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace LeagueManagerWebApp.Controllers
{
    public class LeagueController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeagueController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: League
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var list = _context.LeagueModel.First(a =>
                    a.Players.Contains(_context.PlayerModel
                        .First(b => b.User == ControllerContext.HttpContext.User.Identity.Name).Name));
                var players = list.Players.Split(',');
                List<PlayerModel> playersList = (from elem in players where _context.PlayerModel.ToList().Exists(a => a.Name == elem) select _context.PlayerModel.ToList().First(a => a.Name == elem)).ToList();

                var final = playersList.OrderBy(o => o.Elo).Reverse().ToList();
                return View("LeagueView", final);
            }

            return Redirect("/Identity/Account/Login");
        }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Controllers/PlayerController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LeagueManagerWebApp.Data;
using LeagueManagerWebApp.Interfaces;
using LeagueManagerWebApp.Models;

namespace LeagueManagerWebApp.Controllers
{

    public class PlayerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPlayerService _playerservice;

        public PlayerController(ApplicationDbContext context, IPlayerService playerservice)
        {
            _context = context;
            _playerservice = playerservice;
        }

        // GET: Player
        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated) return Redirect("/Identity/Account/Login");
            var list = await _context.PlayerModel.ToListAsync();
            if (!list.Exists(a=> a.User == ControllerContext.HttpContext.User.Identity.Name))
            {
                return View("CreatePlayer");
            }

            var item = _playerservice.GetPlayerInfo(ControllerContext.HttpContext.User.Identity.Name, list, _context);
            return View("Index", item);

        }

        [HttpPost]
        public IActionResult CreatePlayer(PlayerModel model)
        {
            model.User = ControllerContext.HttpContext.User.Identity.Name;
            model.Elo = 1600;
            model.HasVoted = false;
            _context.PlayerModel.Add(model);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"] - LeagueManagerWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" crossorigin="anonymous">
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-grid.css" crossorigin="anonymous">
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-reboot.css" crossorigin="anonymous">
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap-theme.css" crossorigin="anonymous">
        <link rel="stylesheet" href="/lib/jQuery.menuUI-master/css/jQuery.menuUI.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css"
              asp-fallback-href="/lib/bootstrap/dist/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="/lib/jQuery.menuUI-master/css/jQuery.menuUI.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </environment>
</head>
<body>
    <nav id="menuUI" class="btn navbar navbar-default sidebar position-fixed" style="background-image: linear-gradient(to bottom, #111 0%, #f8f8f8 100%);" role="navigation">
        <div class="main container-fluid" style="margin-left:0px">
            <div class="navbar-header">
                <a class="navbar-header ">League Manager</a>
            </div>
            <br />
            <div class="navbar-collapse">
                <ul class="nav navbar-nav ">
                    <li>
                        <i class="fas fa-home pull-left"></i><a class="btn" asp-controller="Home" asp-action="Index">Strona główna </a>
                    </li>
                    <li>
                        <i class="fas fa-book pull-left"></i><a class="btn" asp-action="Formats" asp-controller="Home">Formaty</a>
                    </li>
                    <li>
                        <i class="fas fa-book pull-left"></i><a class="btn" asp-action="Rules" asp-controller="Home">Zasady</a>
                    </li>

                    <li>
                        <i class="fas fa-chart-bar pull-left"></i><a class="btn pull-left" asp-controller="Player" asp-action="Index">Twoje statystyki</a>
                    </li>
                    <li>
                        <i class="fas fa-trophy pull-left"></i><a class="btn pull-left" asp-controller="Achievement" asp-action="Index">Osiągnięcia</a>
                    </li>
                    <li>
                        <i class="fas fa-star pull-left"></i><a class="btn" asp-controller="League" asp-action="Index">Wyniki ligi</a>
                    </li>
                    <li>
                        <i class="far fa-calendar-alt pull-left"></i><a class="btn" asp-controller="Event" asp-action="Index">Terminarz </a>
                    </li>

                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            <i class="fas fa-tools pull-left"></i><a class="btn" asp-controller="Administrator" asp-action="Index">Administrator</a>
                        </li>
                    }

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li>
                            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new {area = ""})" method="post" id="logoutForm" class="form-inline">

                                <i class="fas fa-sign-out-alt"></i><button type="submit" class="btn btn-link nav-link">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li>
                            <i class="fas fa-sign-in-alt"></i><a asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>


<partial name="_CookieConsentPartial"/>
<div class="main container-fluid ">
    @RenderBody()
    <hr/>
</div>

<script>
    json = {
        brand: 'Menu UI',
        menu: [
            { id: 'home', value: 'Home', icon: 'fa fa-home' },
            { id: 'profile', value: 'Profile', icon: 'glyphicon glyphicon-user' },
            { id: 'message', value: 'Message', icon: 'glyphicon glyphicon-envelope' },
            {
                id: 'setting',
                value: 'Setting',
                icon: 'glyphicon glyphicon-cog',
                submenu: [
                    { id: 'preference', value: 'Preference' }, { id: 'theme', value: 'Theme' },
                    { id: 'help', value: 'Help' }
                ]
            }
        ]
    }
    $("#menuUI").menuUI(json, callBack);
</script>
<script>
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker
            .register('sw.js')
            .then(function() { console.log("Service Worker Registered"); });
    }
</script>
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jQuery.menuUI-master/js/jQuery.menuUI.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery/dist/jquery.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="">
    </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/lib/jQuery.menuUI-master/js/jQuery.menuUI.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>