LeagueManagerWebApp/LeagueManagerWebApp/ViewModels/AchievementsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LeagueManagerWebApp.Models;

namespace LeagueManagerWebApp.ViewModels
{
    public class AchievementsViewModel
    {
        public List<PlayerModel> Players { get; set; }
        public List<AchievementModel> Achievements { get; set; }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Controllers/AchievementController.cs
using LeagueManagerWebApp.Data;
using LeagueManagerWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace LeagueManagerWebApp.Controllers
{
    public class AchievementController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AchievementController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Achievement
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(_context.AchievementModel.ToList().OrderBy(a => a.Points).Reverse());
            }

            return Redirect("/Identity/Account/Login");
        }

        public IActionResult ShowStandings()
        {
            var playersList = _context.PlayerModel.ToList();
            var output = playersList.OrderBy(o => o.AchievementScore).Reverse().ToList();

            return View("StandingsView", output);
        }

        public IActionResult AddAchievement()
        {
            var viewModel = new AchievementsViewModel
            {
                Players = _context.PlayerModel.ToList(),
                Achievements = _context.AchievementModel.ToList()
            };
            return View("AttachAchievement", viewModel);
        }

        [HttpPost]
        public IActionResult SubmitAchievement(string PlayerName, string AchievementName)
        {
            var player = _context.PlayerModel.First(o => o.Name == PlayerName);
            var achievement = _context.AchievementModel.First(o => o.Name == AchievementName);
            player.AchievementScore += achievement.Points;
            player.Achievements = player.Achievements + "|" + AchievementName;
            _context.PlayerModel.Update(player);
            _context.SaveChanges();
            var output = _context.AchievementModel.ToList();

            return View("Index", output.OrderBy(a => a.Points));
        }
    }
}

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/AttachAchievement.cshtml
@model LeagueManagerWebApp.ViewModels.AchievementsViewModel
@{
    ViewData["Title"] = "AttachAchievement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
<h2>AttachAchievement</h2>
<div class="container-fluid">
    <div class="row justify-content-center">
        <form asp-controller="Achievement" asp-action="SubmitAchievement" method="post">
            <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col">
                    Player name: <br />
                </div>
                <div class="col">
                    <select name="PlayerName">
                        @foreach (var elem in Model.Players)
                        {
                            <option value="@(elem.Name)">@(elem.Name)</option>
                        }
                    </select>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        Achievement name: <br />
                    </div>
                    <div class="col">
                        <select name="AchievementName">
                            @foreach (var elem in Model.Achievements)
                            {
                                <option value="@(elem.Name)">@(elem.Name)</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col">
                        <input type="submit" />
                    </div>

                </div>
            </div>
            </div>
        </form>
    </div>
</div>
</body>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/Create.cshtml
@model LeagueManagerWebApp.Models.AchievementModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>AchievementModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/Delete.cshtml
@model LeagueManagerWebApp.Models.AchievementModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AchievementModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/Details.cshtml
@model LeagueManagerWebApp.Models.AchievementModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>AchievementModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/Edit.cshtml
@model LeagueManagerWebApp.Models.AchievementModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>AchievementModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<LeagueManagerWebApp.Models.AchievementModel>
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Index";
}

<body>

    <div class="row">
        <h2 class="display-2">Osiągnięcia</h2>
    </div>
    <div class="row">
        <div class="col-6">
            <p>
                <a class="btn btn-lg btn-primary btn-block" asp-action="ShowStandings">Ranking</a>
            </p>
        </div>
        @if (User.IsInRole("Admin"))
        {
            <div class="col-6">
                <a class="btn btn-lg btn-primary btn-block" asp-action="AddAchievement">Przydziel osiągnięcie</a>
            </div>
        }
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table table-striped table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Points)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td scope="row" data-label="Nazwa">
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td data-label="Opis">
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td data-label="Punkty">
                                @Html.DisplayFor(modelItem => item.Points)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

LeagueManagerWebApp/LeagueManagerWebApp/Views/Achievement/StandingsView.cshtml
@model List<PlayerModel>
@{
    ViewData["Title"] = "StandingsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <div class="container">
        <div class="row justify-content-center">
            <h2 class="display-2">Ranking</h2>
        </div>
        <div class="row">
            <div class="col">
                <p>
                    <a class="btn btn-lg btn-primary btn-block" asp-action="Index">Powrót</a>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">
                                Gracz
                            </th>
                            <th scope="col">
                                Wynik
                            </th>
                            <th scope="col">
                                Lista osiągnięć
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row" data-label="Gracz">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td data-label="Wynik">
                                    @Html.DisplayFor(modelItem => item.AchievementScore)
                                </td>
                                <td data-label="Lista osiągnięć">
                                    @Html.DisplayFor(modelItem => item.Achievements)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>